program Zugriffsfunktionen 
with
    var s := pair(a,b);
begin
    query fst(pair) for X ?- pair ~ pair(X,Y) end
    query setFst(pair,val) for X ?- 
        pair ~ pair(Fst,Snd), X ~ pair(val,Snd) 
    end

    query tf() for X ?- X ~ true ; X ~ false end

    proc main() 
    does
        if tf() then
            return firstOf(fst($s),$s); 
        else 
            s := setFst($s, 1);
            return modified(fst($s),$s);
        end
    end
end
